question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Geography",
     "question": "The two largest ethnic groups of Belgium are Flemish and Walloon. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "Rabbits are rodents.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows ME operating system was released in the year 2000.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Board Games",
     "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The Cold War ended with Joseph Stalin&#039;s death.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "There are no roads in/out of Juneau, Alaska.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The USS Missouri (BB-63) last served in the Korean War.",
     "correct_answer": "False", "incorrect_answers": ["True"]}
]
